
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async greet(name: string) : Promise<string> {
    return await TAURI_INVOKE("greet", { name });
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type ArbBet = { sport_key: string; event_id: string; home_team: string; away_team: string; market: string; book_a: string; book_a_title: string; outcome_a: string; odds_a: number; point_a?: number | null; book_b: string; book_b_title: string; outcome_b: string; odds_b: number; point_b?: number | null; profit_pct: number; implied_sum: number; player_name?: string | null; is_prop?: boolean }
export type Bookmaker = { key: string; title: string; last_update?: string | null; markets?: Market[] }
export type EVBet = { sport_key: string; book: string; book_title: string; event_id: string; home_team: string; away_team: string; market: string; outcome_name: string; outcome_point?: number | null; odds: number; decimal_odds: number; implied_prob: number; no_vig_prob: number; fair_odds: number; ev_percentage: number; edge: number; detected_at?: string | null; num_books?: number; player_name?: string | null; is_prop?: boolean }
export type Event = { id: string; sport_key: string; sport_title?: string; commence_time: string; home_team: string; away_team: string; bookmakers?: Bookmaker[] }
export type GameRow = { event_id: string; sport_key: string; home_team: string; away_team: string; commence_time: string; home_score?: string; away_score?: string; completed?: boolean; bookmakers?: Bookmaker[] }
export type Market = { key: string; last_update?: string | null; outcomes?: OutcomeOdds[] }
export type MiddleBet = { sport_key: string; event_id: string; home_team: string; away_team: string; market: string; book_a: string; book_a_title: string; line_a: number; odds_a: number; outcome_a: string; book_b: string; book_b_title: string; line_b: number; odds_b: number; outcome_b: string; middle_low: number; middle_high: number; window_size: number; combined_cost: number; hit_prob?: number; ev_percentage?: number; player_name?: string | null; is_prop?: boolean }
export type OutcomeOdds = { name: string; price: number; point?: number | null; description?: string | null }
export type PropRow = { event_id: string; sport_key: string; home_team: string; away_team: string; commence_time: string; player_name: string; market_key: string; consensus_point?: number | null; over_odds?: Partial<{ [key in string]: number }>; under_odds?: Partial<{ [key in string]: number }> }
export type Score = { id: string; sport_key: string; sport_title?: string; commence_time: string; home_team: string; away_team: string; completed?: boolean; last_update?: string | null; scores?: ScoreValue[] | null }
export type ScoreValue = { name: string; score?: string | null }
export type Settings = { bookmakers?: string[]; ev_reference?: string; sports?: string[]; odds_refresh_interval?: number; scores_refresh_interval?: number; ev_threshold?: number; ev_odds_min?: number; ev_odds_max?: number; odds_format?: string; regions?: string[]; low_credit_warning?: number; critical_credit_stop?: number; props_enabled?: boolean; props_refresh_interval?: number; props_max_concurrent?: number; alt_lines_enabled?: boolean; arb_enabled?: boolean; arb_min_profit_pct?: number; middle_enabled?: boolean; middle_min_window?: number; middle_max_combined_cost?: number; dfs_books?: Partial<{ [key in string]: number }>; props_markets?: Partial<{ [key in string]: string[] }> }
export type Sport = { key: string; group: string; title: string; description?: string; active?: boolean; has_outrights?: boolean }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
