//! Parity tests against Python goldens generated by
//! `python-legacy/scripts/generate_engine_fixtures.py`.
//!
//! For each detection function, Rust output is sorted with the same
//! deterministic total order as the Python dump and compared field-by-field
//! with floats within 1e-6. `detected_at` is intentionally skipped because
//! Python sets it to None before dumping.

use oddsdesk_lib::engine::{
    find_arb_bets, find_ev_bets, find_middle_bets, find_prop_arb_bets, find_prop_middle_bets,
    EvOptions,
};
use oddsdesk_lib::models::{ArbBet, EVBet, Event, MiddleBet};
use std::path::PathBuf;

const EPS: f64 = 1e-6;

fn fixture_path(rel: &str) -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("tests")
        .join("fixtures")
        .join("engine")
        .join(rel)
}

fn load_events(name: &str) -> Vec<Event> {
    let text = std::fs::read_to_string(fixture_path(name))
        .unwrap_or_else(|e| panic!("read {name}: {e}"));
    serde_json::from_str(&text).unwrap_or_else(|e| panic!("parse {name}: {e}"))
}

fn load_json<T: serde::de::DeserializeOwned>(name: &str) -> T {
    let text = std::fs::read_to_string(fixture_path(name))
        .unwrap_or_else(|e| panic!("read {name}: {e}"));
    serde_json::from_str(&text).unwrap_or_else(|e| panic!("parse {name}: {e}"))
}

fn approx(a: f64, b: f64, ctx: &str) {
    let d = (a - b).abs();
    assert!(d < EPS, "{ctx}: |{a} - {b}| = {d} > {EPS}");
}

fn approx_opt(a: Option<f64>, b: Option<f64>, ctx: &str) {
    match (a, b) {
        (None, None) => {}
        (Some(x), Some(y)) => approx(x, y, ctx),
        _ => panic!("{ctx}: one side is None, the other is Some"),
    }
}

fn assert_ev_parity(rust: &[EVBet], golden: &[EVBet]) {
    assert_eq!(rust.len(), golden.len(), "bet count mismatch");
    for (i, (r, g)) in rust.iter().zip(golden.iter()).enumerate() {
        assert_eq!(r.sport_key, g.sport_key, "sport_key @ {i}");
        assert_eq!(r.event_id, g.event_id, "event_id @ {i}");
        assert_eq!(r.book, g.book, "book @ {i}");
        assert_eq!(r.book_title, g.book_title, "book_title @ {i}");
        assert_eq!(r.home_team, g.home_team, "home_team @ {i}");
        assert_eq!(r.away_team, g.away_team, "away_team @ {i}");
        assert_eq!(r.market, g.market, "market @ {i}");
        assert_eq!(r.outcome_name, g.outcome_name, "outcome_name @ {i}");
        approx_opt(r.outcome_point, g.outcome_point, &format!("outcome_point @ {i}"));
        approx(r.odds, g.odds, &format!("odds @ {i}"));
        approx(r.decimal_odds, g.decimal_odds, &format!("decimal_odds @ {i}"));
        approx(r.implied_prob, g.implied_prob, &format!("implied_prob @ {i}"));
        approx(r.no_vig_prob, g.no_vig_prob, &format!("no_vig_prob @ {i}"));
        approx(r.fair_odds, g.fair_odds, &format!("fair_odds @ {i}"));
        approx(r.ev_percentage, g.ev_percentage, &format!("ev_percentage @ {i}"));
        approx(r.edge, g.edge, &format!("edge @ {i}"));
        assert_eq!(r.num_books, g.num_books, "num_books @ {i}");
        assert_eq!(r.player_name, g.player_name, "player_name @ {i}");
        assert_eq!(r.is_prop, g.is_prop, "is_prop @ {i}");
        // detected_at skipped — Python sets None before dump, Rust sets Utc::now()
    }
}

fn assert_arb_parity(rust: &[ArbBet], golden: &[ArbBet]) {
    assert_eq!(rust.len(), golden.len(), "arb count mismatch");
    for (i, (r, g)) in rust.iter().zip(golden.iter()).enumerate() {
        assert_eq!(r.sport_key, g.sport_key, "sport_key @ {i}");
        assert_eq!(r.event_id, g.event_id, "event_id @ {i}");
        assert_eq!(r.market, g.market, "market @ {i}");
        assert_eq!(r.book_a, g.book_a, "book_a @ {i}");
        assert_eq!(r.book_b, g.book_b, "book_b @ {i}");
        assert_eq!(r.outcome_a, g.outcome_a, "outcome_a @ {i}");
        assert_eq!(r.outcome_b, g.outcome_b, "outcome_b @ {i}");
        approx(r.odds_a, g.odds_a, &format!("odds_a @ {i}"));
        approx(r.odds_b, g.odds_b, &format!("odds_b @ {i}"));
        approx_opt(r.point_a, g.point_a, &format!("point_a @ {i}"));
        approx_opt(r.point_b, g.point_b, &format!("point_b @ {i}"));
        approx(r.profit_pct, g.profit_pct, &format!("profit_pct @ {i}"));
        approx(r.implied_sum, g.implied_sum, &format!("implied_sum @ {i}"));
        assert_eq!(r.player_name, g.player_name, "player_name @ {i}");
        assert_eq!(r.is_prop, g.is_prop, "is_prop @ {i}");
    }
}

fn assert_middle_parity(rust: &[MiddleBet], golden: &[MiddleBet]) {
    assert_eq!(rust.len(), golden.len(), "middle count mismatch");
    for (i, (r, g)) in rust.iter().zip(golden.iter()).enumerate() {
        assert_eq!(r.sport_key, g.sport_key, "sport_key @ {i}");
        assert_eq!(r.event_id, g.event_id, "event_id @ {i}");
        assert_eq!(r.market, g.market, "market @ {i}");
        assert_eq!(r.book_a, g.book_a, "book_a @ {i}");
        assert_eq!(r.book_b, g.book_b, "book_b @ {i}");
        assert_eq!(r.outcome_a, g.outcome_a, "outcome_a @ {i}");
        assert_eq!(r.outcome_b, g.outcome_b, "outcome_b @ {i}");
        approx(r.line_a, g.line_a, &format!("line_a @ {i}"));
        approx(r.line_b, g.line_b, &format!("line_b @ {i}"));
        approx(r.odds_a, g.odds_a, &format!("odds_a @ {i}"));
        approx(r.odds_b, g.odds_b, &format!("odds_b @ {i}"));
        approx(r.middle_low, g.middle_low, &format!("middle_low @ {i}"));
        approx(r.middle_high, g.middle_high, &format!("middle_high @ {i}"));
        approx(r.window_size, g.window_size, &format!("window_size @ {i}"));
        approx(r.combined_cost, g.combined_cost, &format!("combined_cost @ {i}"));
        approx(r.hit_prob, g.hit_prob, &format!("hit_prob @ {i}"));
        approx(r.ev_percentage, g.ev_percentage, &format!("ev_percentage @ {i}"));
        assert_eq!(r.player_name, g.player_name, "player_name @ {i}");
        assert_eq!(r.is_prop, g.is_prop, "is_prop @ {i}");
    }
}

#[test]
fn ev_bets_game_parity() {
    let events = load_events("events_game.json");
    let golden: Vec<EVBet> = load_json("golden/ev_bets_game.json");
    let opts = EvOptions { ev_threshold: -100.0, ..Default::default() };
    let rust = find_ev_bets(&events, opts);
    assert_ev_parity(&rust, &golden);
}

#[test]
fn ev_bets_props_parity() {
    let events = load_events("events_props.json");
    let golden: Vec<EVBet> = load_json("golden/ev_bets_props.json");
    let opts = EvOptions { is_props: true, ev_threshold: -100.0, ..Default::default() };
    let rust = find_ev_bets(&events, opts);
    assert_ev_parity(&rust, &golden);
}

#[test]
fn arbs_game_parity() {
    let events = load_events("events_game.json");
    let golden: Vec<ArbBet> = load_json("golden/arbs_game.json");
    let rust = find_arb_bets(&events, 0.0, None);
    assert_arb_parity(&rust, &golden);
}

#[test]
fn arbs_props_parity() {
    let events = load_events("events_props.json");
    let golden: Vec<ArbBet> = load_json("golden/arbs_props.json");
    let rust = find_prop_arb_bets(&events, 0.0, None);
    assert_arb_parity(&rust, &golden);
}

#[test]
fn middles_game_parity() {
    let events = load_events("events_game.json");
    let golden: Vec<MiddleBet> = load_json("golden/middles_game.json");
    let rust = find_middle_bets(&events, 0.5, 1.08, None);
    assert_middle_parity(&rust, &golden);
}

#[test]
fn middles_props_parity() {
    let events = load_events("events_props.json");
    let golden: Vec<MiddleBet> = load_json("golden/middles_props.json");
    let rust = find_prop_middle_bets(&events, 0.5, 1.08, None);
    assert_middle_parity(&rust, &golden);
}
